version: '3'

networks:
  grafana:
    driver: bridge

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    expose:
      - "8086"
    environment:
      - INFLUXDB_DB=k6
    volumes:
      - ./influxdb_data:/var/lib/influxdb
    networks:
      - grafana
      # - k6

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      # - GF_SECURITY_ADMIN_USER=admin
      # - GF_SECURITY_ADMIN_PASSWORD=__temp#
      # - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana:/etc/grafana/provisioning/


  # k6:
  #   image: grafana/k6:latest
  #   networks:
  #     - k6
  #   ports:
  #     - "6565:6565"
  #   environment:
  #     - K6_OUT=influxdb=http://influxdb:8086/k6
  #   volumes:
  #     - ./scripts:/scripts
  #   depends_on:
  #     - influxdb
    
